FROM node:latest

# RUN apk update

RUN npm install --global nodemon

ENV NODE_ENV development

RUN mkdir -p /usr/src/app/worker/node_modules && chown -R node:node /usr/src/app/worker

WORKDIR /usr/src/app/worker

COPY package*.json ./

COPY tsconfig.json ./

USER node

RUN npm install

COPY --chown=node:node ./ /usr/src/app/worker

CMD ["npm", "run", "worker"]