version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web.dev
    volumes:
      - ./:/usr/src/app/web
      - /usr/src/app/web/node_modules
    env_file: .env
    ports:
      - "$PORT:$PORT"
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker.dev
    volumes:
      - ./:/usr/src/app/worker
      - /usr/src/app/worker/node_modules
    env_file: .env